version: '3.8'
services:
  activemq:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ACTIVE_MQ_USERNAME=test
      - ACTIVE_MQ_PASSWORD=test
    ports:
      - "8161:8161"
      - "61616:61616"