version: '3.8'
services:
  activemq:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ACTIVE_MQ_USERNAME=""
      - ACTIVE_MQ_PASSWORD=""
    ports:
      - "8161:8161"
      - "61616:61616"